frontend:
  namespace: frontend-dev
  image: ghcr.io/bankmarkbenz/front-end
  tag: dev
  replicas: 1
  imagePullSecrets: registry
  port: 80
  healthCheckPath: "/health.html"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: dev.bankandmark.codes
  path: "/*(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_SHA: CHANGEME
