frontend:
  namespace: frontend-uat
  image: ghcr.io/BankMarkBenz/front-end
  tag: uat
  replicas: 1
  imagePullSecrets: registry
  port: 80
  healthCheckPath: "/health.html"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: uat.bankandmark.codes
  path: "/frontend(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_SHA: CHANGEME