apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
#  {{- if .Values.ingress.annotations }}
#  annotations:
#  {{- range $key, $value := .Values.ingress.annotations }}
#  {{ $key }}: {{ $value | quote }}
#  {{- end }}
#  {{- end }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: {{ .Release.Name }}
  namespace: {{ .Values.backend.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.backend.port }}