apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.frontend.namespace }}
spec:
  type: {{ .Values.ingress.serviceType }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
  selector:
    app: {{ .Release.Name }}