name: dev-env
on:
  push:
    branches:
      - dev
      - deploy
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: sijomc/sonarscan-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: ${{ secrets.SONARQUBE_PROJECTKEY }}
          projectName: ${{ secrets.SONARQUBE_PROJECTKEY }}       
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bankmarkbenz/frontend:dev
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: bankmarkbenz-cluster
          location: asia-east1-a
          credentials: ${{ secrets.GKE_CREDENTIALS }}
      - name: deploy
        uses: "deliverybot/helm@v1"
        with:
          helm: helm3
          release: frontend-dev-service
          namespace: frontend-dev
          chart: k8s/helm
          value-files: k8s/helm-values/values-frontend-dev.yaml
          values: |
            {
              "extraEnv": {
                "COMMIT_SHA": "${{ github.sha }}"
              }
            }